//
//  Presidents.m
//  USPresidents
//
//  Created by Lisa Ridley on 8/31/11.
//  Copyright 2011 RoveWorks. All rights reserved.
//

#import "Presidents.h"

@implementation Presidents
@synthesize presInfo;
- (id)init
{
    self = [super init];
    if (self) {
        NSMutableDictionary *pres1 = [[NSMutableDictionary alloc]initWithCapacity:14];
        [pres1 setObject:@"George Washington" forKey:@"name"];
        [pres1 setObject:@"02/22/1732" forKey:@"dob"];
        [pres1 setObject:@"Pope's Creek, Virginia" forKey:@"pob"];
        [pres1 setObject:@"12/14/1799" forKey:@"dod"];
        [pres1 setObject:@"Mount Vernon, Virginia" forKey:@"pod"];
        [pres1 setObject:@"04/30/1789" forKey:@"tookOffice"];
        [pres1 setObject:@"03/04/1797" forKey:@"leftOffice"];
        [pres1 setObject:@"2" forKey:@"terms"];
        [pres1 setObject:@"natural causes (illness)" forKey:@"causeOfDeath"];
        [pres1 setObject:@"N" forKey:@"diedInOffice"];
        [pres1 setObject:@"N" forKey:@"assassinated"];
        [pres1 setObject:@"Federalist" forKey:@"politicalParty"];
        [pres1 setObject:@"John Adams" forKey:@"vicePres"];
        [pres1 setObject:@"GeorgeWashington.png" forKey:@"photo"];

        NSMutableDictionary *pres2 = [[NSMutableDictionary alloc]initWithCapacity:14];
        [pres2 setObject:@"John Adams, Jr." forKey:@"name"];
        [pres2 setObject:@"10/30/1735" forKey:@"dob"];
        [pres2 setObject:@"Braintree, Massachusetts" forKey:@"pob"];
        [pres2 setObject:@"07/04/1826" forKey:@"dod"];
        [pres2 setObject:@"Quincy, Massachusetts" forKey:@"pod"];
        [pres2 setObject:@"03/04/1797" forKey:@"tookOffice"];
        [pres2 setObject:@"03/04/1801" forKey:@"leftOffice"];
        [pres2 setObject:@"1" forKey:@"terms"];
        [pres2 setObject:@"natural causes" forKey:@"causeOfDeath"];
        [pres2 setObject:@"N" forKey:@"diedInOffice"];
        [pres2 setObject:@"N" forKey:@"assassinated"];
        [pres2 setObject:@"Federalist" forKey:@"politicalParty"];
        [pres2 setObject:@"Thomas Jefferson" forKey:@"vicePres"];
        [pres2 setObject:@"JohnAdams.png" forKey:@"photo"];

        NSMutableDictionary *pres3 = [[NSMutableDictionary alloc]initWithCapacity:14];
        [pres3 setObject:@"Thomas Jefferson" forKey:@"name"];
        [pres3 setObject:@"04/13/1743" forKey:@"dob"];
        [pres3 setObject:@"Shadwell plantation, Goochland County, Virginia" forKey:@"pob"];
        [pres3 setObject:@"07/04/1826" forKey:@"dod"];
        [pres3 setObject:@"Monticello, near Charlottesville, Virginia" forKey:@"pod"];
        [pres3 setObject:@"03/04/1801" forKey:@"tookOffice"];
        [pres3 setObject:@"03/04/1809" forKey:@"leftOffice"];
        [pres3 setObject:@"2" forKey:@"terms"];
        [pres3 setObject:@"natural causes" forKey:@"causeOfDeath"];
        [pres3 setObject:@"N" forKey:@"diedInOffice"];
        [pres3 setObject:@"N" forKey:@"assassinated"];
        [pres3 setObject:@"Democratic-Republican" forKey:@"politicalParty"];
        [pres3 setObject:@"Aaron Burr, George Clinton" forKey:@"vicePres"];
        [pres3 setObject:@"ThomasJefferson.png" forKey:@"photo"];
        
        NSMutableDictionary *pres4 = [[NSMutableDictionary alloc]initWithCapacity:14];
        [pres4 setObject:@"James Madison, Jr." forKey:@"name"];
        [pres4 setObject:@"03/16/1751" forKey:@"dob"];
        [pres4 setObject:@"Belle Grove Plantation, near Port Conway Virginia" forKey:@"pob"];
        [pres4 setObject:@"06/28/1836" forKey:@"dod"];
        [pres4 setObject:@"Montpelier, near Orange, Virginia" forKey:@"pod"];
        [pres4 setObject:@"03/04/1809" forKey:@"tookOffice"];
        [pres4 setObject:@"03/04/1817" forKey:@"leftOffice"];
        [pres4 setObject:@"2" forKey:@"terms"];
        [pres4 setObject:@"natural causes" forKey:@"causeOfDeath"];
        [pres4 setObject:@"N" forKey:@"diedInOffice"];
        [pres4 setObject:@"N" forKey:@"assassinated"];
        [pres4 setObject:@"Democratic-Republican" forKey:@"politicalParty"];
        [pres4 setObject:@"George Clinton, Elbridge Gerry" forKey:@"vicePres"];
        [pres4 setObject:@"JamesMadison.png" forKey:@"photo"];

        NSMutableDictionary *pres5 = [[NSMutableDictionary alloc]initWithCapacity:14];
        [pres5 setObject:@"James Monroe" forKey:@"name"];
        [pres5 setObject:@"04/28/1758" forKey:@"dob"];
        [pres5 setObject:@"Westmoreland County, Virginia" forKey:@"pob"];
        [pres5 setObject:@"07/04/1831" forKey:@"dod"];
        [pres5 setObject:@"New York City, New York" forKey:@"pod"];
        [pres5 setObject:@"03/04/1817" forKey:@"tookOffice"];
        [pres5 setObject:@"03/04/1825" forKey:@"leftOffice"];
        [pres5 setObject:@"2" forKey:@"terms"];
        [pres5 setObject:@"natural causes (heart failure and tuberculosis)" forKey:@"causeOfDeath"];
        [pres5 setObject:@"N" forKey:@"diedInOffice"];
        [pres5 setObject:@"N" forKey:@"assassinated"];
        [pres5 setObject:@"Democratic-Republican" forKey:@"politicalParty"];
        [pres5 setObject:@"Daniel Tompkins" forKey:@"vicePres"];
        [pres5 setObject:@"JamesMonroe.png" forKey:@"photo"];
        
        NSMutableDictionary *pres6 = [[NSMutableDictionary alloc]initWithCapacity:14];
        [pres6 setObject:@"John Quincy Adams" forKey:@"name"];
        [pres6 setObject:@"07/11/1767" forKey:@"dob"];
        [pres6 setObject:@"Braintree, Massachusetts" forKey:@"pob"];
        [pres6 setObject:@"02/23/1848" forKey:@"dod"];
        [pres6 setObject:@"Washington, D.C." forKey:@"pod"];
        [pres6 setObject:@"03/04/1825" forKey:@"tookOffice"];
        [pres6 setObject:@"03/04/1829" forKey:@"leftOffice"];
        [pres6 setObject:@"1" forKey:@"terms"];
        [pres6 setObject:@"natural causes (cerebral hemorrhage)" forKey:@"causeOfDeath"];
        [pres6 setObject:@"N" forKey:@"diedInOffice"];
        [pres6 setObject:@"N" forKey:@"assassinated"];
        [pres6 setObject:@"Democratic-Republican; National Republican" forKey:@"politicalParty"];
        [pres6 setObject:@"John Calhoun" forKey:@"vicePres"];
        [pres6 setObject:@"JohnQAdams.png" forKey:@"photo"];

        NSMutableDictionary *pres7 = [[NSMutableDictionary alloc]initWithCapacity:14];
        [pres7 setObject:@"Andrew Jackson" forKey:@"name"];
        [pres7 setObject:@"03/15/1767" forKey:@"dob"];
        [pres7 setObject:@"near Waxhaw, North Carolina" forKey:@"pob"];
        [pres7 setObject:@"06/08/1845" forKey:@"dod"];
        [pres7 setObject:@"Nashville, Tennessee" forKey:@"pod"];
        [pres7 setObject:@"03/04/1829" forKey:@"tookOffice"];
        [pres7 setObject:@"03/04/1837" forKey:@"leftOffice"];
        [pres7 setObject:@"2" forKey:@"terms"];
        [pres7 setObject:@"natural causes (tuberculosis, dropsy, heart failure)" forKey:@"causeOfDeath"];
        [pres7 setObject:@"N" forKey:@"diedInOffice"];
        [pres7 setObject:@"N" forKey:@"assassinated"];
        [pres7 setObject:@"Democratic" forKey:@"politicalParty"];
        [pres7 setObject:@"John C. Calhoun; Martin Van Buren" forKey:@"vicePres"];
        [pres7 setObject:@"AndrewJackson.png" forKey:@"photo"];

        NSMutableDictionary *pres8 = [[NSMutableDictionary alloc]initWithCapacity:14];
        [pres8 setObject:@"Martin Van Buren" forKey:@"name"];
        [pres8 setObject:@"12/05/1782" forKey:@"dob"];
        [pres8 setObject:@"Kinderhook, New York" forKey:@"pob"];
        [pres8 setObject:@"07/24/1862" forKey:@"dod"];
        [pres8 setObject:@"Kinderhook, New York" forKey:@"pod"];
        [pres8 setObject:@"03/04/1837" forKey:@"tookOffice"];
        [pres8 setObject:@"03/04/1841" forKey:@"leftOffice"];
        [pres8 setObject:@"1" forKey:@"terms"];
        [pres8 setObject:@"natural causes (asthma, heart failure)" forKey:@"causeOfDeath"];
        [pres8 setObject:@"N" forKey:@"diedInOffice"];
        [pres8 setObject:@"N" forKey:@"assassinated"];
        [pres8 setObject:@"Democratic" forKey:@"politicalParty"];
        [pres8 setObject:@"Richard Mentor Johnson" forKey:@"vicePres"];
        [pres8 setObject:@"MartinVanBuren.png" forKey:@"photo"];

        NSMutableDictionary *pres9 = [[NSMutableDictionary alloc]initWithCapacity:14];
        [pres9 setObject:@"William Henry Harrison" forKey:@"name"];
        [pres9 setObject:@"02/09/1773" forKey:@"dob"];
        [pres9 setObject:@"Berkeley plantation, Charles City County, Virginia" forKey:@"pob"];
        [pres9 setObject:@"03/04/1841" forKey:@"dod"];
        [pres9 setObject:@"Washington, D.C." forKey:@"pod"];
        [pres9 setObject:@"93/94/1841" forKey:@"tookOffice"];
        [pres9 setObject:@"04/04/1841" forKey:@"leftOffice"];
        [pres9 setObject:@"1" forKey:@"terms"];
        [pres9 setObject:@"natural causes (pneumonia)" forKey:@"causeOfDeath"];
        [pres9 setObject:@"Y" forKey:@"diedInOffice"];
        [pres9 setObject:@"N" forKey:@"assassinated"];
        [pres9 setObject:@"Whig" forKey:@"politicalParty"];
        [pres9 setObject:@"John Tyler" forKey:@"vicePres"];
        [pres9 setObject:@"WilliamHHarrison.png" forKey:@"photo"];

        NSMutableDictionary *pres10 = [[NSMutableDictionary alloc]initWithCapacity:14];
        [pres10 setObject:@"John Tyler" forKey:@"name"];
        [pres10 setObject:@"03/29/1790" forKey:@"dob"];
        [pres10 setObject:@"Charles City County, Virginia" forKey:@"pob"];
        [pres10 setObject:@"01/18/1862" forKey:@"dod"];
        [pres10 setObject:@"Richmond, Virginia" forKey:@"pod"];
        [pres10 setObject:@"04/04/1841" forKey:@"tookOffice"];
        [pres10 setObject:@"03/04/1845" forKey:@"leftOffice"];
        [pres10 setObject:@"1" forKey:@"terms"];
        [pres10 setObject:@"natural causes (dysentery)" forKey:@"causeOfDeath"];
        [pres10 setObject:@"N" forKey:@"diedInOffice"];
        [pres10 setObject:@"N" forKey:@"assassinated"];
        [pres10 setObject:@"Whig; no party" forKey:@"politicalParty"];
        [pres10 setObject:@"None" forKey:@"vicePres"];
        [pres10 setObject:@"JohnTyler.png" forKey:@"photo"];

        NSMutableDictionary *pres11 = [[NSMutableDictionary alloc]initWithCapacity:14];
        [pres11 setObject:@"James Knox Polk" forKey:@"name"];
        [pres11 setObject:@"11/02/1795" forKey:@"dob"];
        [pres11 setObject:@"Mecklenburg County, North Carolina" forKey:@"pob"];
        [pres11 setObject:@"06/15/1849" forKey:@"dod"];
        [pres11 setObject:@"Nashville, Tennessee" forKey:@"pod"];
        [pres11 setObject:@"03/04/1845" forKey:@"tookOffice"];
        [pres11 setObject:@"03/04/1849" forKey:@"leftOffice"];
        [pres11 setObject:@"1" forKey:@"terms"];
        [pres11 setObject:@"natural causes (cholera)" forKey:@"causeOfDeath"];
        [pres11 setObject:@"N" forKey:@"diedInOffice"];
        [pres11 setObject:@"N" forKey:@"assassinated"];
        [pres11 setObject:@"Democratic" forKey:@"politicalParty"];
        [pres11 setObject:@"George Mifflin Dallas" forKey:@"vicePres"];
        [pres11 setObject:@"JamesPolk.png" forKey:@"photo"];

        NSMutableDictionary *pres12 = [[NSMutableDictionary alloc]initWithCapacity:14];
        [pres12 setObject:@"Zachary Taylor" forKey:@"name"];
        [pres12 setObject:@"11/24/1784" forKey:@"dob"];
        [pres12 setObject:@"near Barboursville, Virginia" forKey:@"pob"];
        [pres12 setObject:@"07/09/1850" forKey:@"dod"];
        [pres12 setObject:@"Washington, D.C." forKey:@"pod"];
        [pres12 setObject:@"03/04/1849" forKey:@"tookOffice"];
        [pres12 setObject:@"07.09.1850" forKey:@"leftOffice"];
        [pres12 setObject:@"1" forKey:@"terms"];
        [pres12 setObject:@"natural causes (acute gastroenteritis)" forKey:@"causeOfDeath"];
        [pres12 setObject:@"Y" forKey:@"diedInOffice"];
        [pres12 setObject:@"N" forKey:@"assassinated"];
        [pres12 setObject:@"Whig" forKey:@"politicalParty"];
        [pres12 setObject:@"Millard Fillmore" forKey:@"vicePres"];
        [pres12 setObject:@"ZacharyTaylor.png" forKey:@"photo"];

        NSMutableDictionary *pres13 = [[NSMutableDictionary alloc]initWithCapacity:14];
        [pres13 setObject:@"Millard Fillmore" forKey:@"name"];
        [pres13 setObject:@"01/07/1800" forKey:@"dob"];
        [pres13 setObject:@"Summerhill, New York" forKey:@"pob"];
        [pres13 setObject:@"03/08/1874" forKey:@"dod"];
        [pres13 setObject:@"Buffalo, New York" forKey:@"pod"];
        [pres13 setObject:@"07/09/1850" forKey:@"tookOffice"];
        [pres13 setObject:@"03/04/1853" forKey:@"leftOffice"];
        [pres13 setObject:@"1" forKey:@"terms"];
        [pres13 setObject:@"natural causes (stroke)" forKey:@"causeOfDeath"];
        [pres13 setObject:@"N" forKey:@"diedInOffice"];
        [pres13 setObject:@"N" forKey:@"assassinated"];
        [pres13 setObject:@"Whig" forKey:@"politicalParty"];
        [pres13 setObject:@"None" forKey:@"vicePres"];
        [pres13 setObject:@"MillardFillmore.png" forKey:@"photo"];

        NSMutableDictionary *pres14 = [[NSMutableDictionary alloc]initWithCapacity:14];
        [pres14 setObject:@"Franklin Pierce" forKey:@"name"];
        [pres14 setObject:@"11/23/1804" forKey:@"dob"];
        [pres14 setObject:@"Hillsborough, New Hampshire" forKey:@"pob"];
        [pres14 setObject:@"10/08/1869" forKey:@"dod"];
        [pres14 setObject:@"Concord, New Hampshire" forKey:@"pod"];
        [pres14 setObject:@"03/04/1853" forKey:@"tookOffice"];
        [pres14 setObject:@"03/04/1857" forKey:@"leftOffice"];
        [pres14 setObject:@"1" forKey:@"terms"];
        [pres14 setObject:@"natural causes" forKey:@"causeOfDeath"];
        [pres14 setObject:@"N" forKey:@"diedInOffice"];
        [pres14 setObject:@"N" forKey:@"assassinated"];
        [pres14 setObject:@"Democratic" forKey:@"politicalParty"];
        [pres14 setObject:@"None" forKey:@"vicePres"];
        [pres14 setObject:@"FranklinPierce.png" forKey:@"photo"];

        NSMutableDictionary *pres15 = [[NSMutableDictionary alloc]initWithCapacity:14];
        [pres15 setObject:@"James Buchanan, Jr." forKey:@"name"];
        [pres15 setObject:@"04/23/1791" forKey:@"dob"];
        [pres15 setObject:@"Cove Gap, Pennsylvania" forKey:@"pob"];
        [pres15 setObject:@"06/01/1868" forKey:@"dod"];
        [pres15 setObject:@"Lancaster, Pennsylvania" forKey:@"pod"];
        [pres15 setObject:@"03/04/1857" forKey:@"tookOffice"];
        [pres15 setObject:@"03/04/1861" forKey:@"leftOffice"];
        [pres15 setObject:@"1" forKey:@"terms"];
        [pres15 setObject:@"natural causes" forKey:@"causeOfDeath"];
        [pres15 setObject:@"N" forKey:@"diedInOffice"];
        [pres15 setObject:@"N" forKey:@"assassinated"];
        [pres15 setObject:@"Democratic" forKey:@"politicalParty"];
        [pres15 setObject:@"John Cabell Breckenridge" forKey:@"vicePres"];
        [pres15 setObject:@"JamesBuchanan.png" forKey:@"photo"];
        
        NSMutableDictionary *pres16 = [[NSMutableDictionary alloc]initWithCapacity:14];
        [pres16 setObject:@"Abraham Lincoln" forKey:@"name"];
        [pres16 setObject:@"02/12/1809" forKey:@"dob"];
        [pres16 setObject:@"Hardin County, Kentucky" forKey:@"pob"];
        [pres16 setObject:@"04/15/1865" forKey:@"dod"];
        [pres16 setObject:@"Washington, D.C." forKey:@"pod"];
        [pres16 setObject:@"03/04/1861" forKey:@"tookOffice"];
        [pres16 setObject:@"04/15/1865" forKey:@"leftOffice"];
        [pres16 setObject:@"1" forKey:@"terms"];
        [pres16 setObject:@"gunshot wound" forKey:@"causeOfDeath"];
        [pres16 setObject:@"Y" forKey:@"diedInOffice"];
        [pres16 setObject:@"Y" forKey:@"assassinated"];
        [pres16 setObject:@"Republican" forKey:@"politicalParty"];
        [pres16 setObject:@"Hannibal Hamlin; Andrew Johnson" forKey:@"vicePres"];
        [pres16 setObject:@"AbrahamLincoln.png" forKey:@"photo"];

        NSMutableDictionary *pres17 = [[NSMutableDictionary alloc]initWithCapacity:14];
        [pres17 setObject:@"Andrew Johnson" forKey:@"name"];
        [pres17 setObject:@"12/29/1808" forKey:@"dob"];
        [pres17 setObject:@"Raleigh, North Carolina" forKey:@"pob"];
        [pres17 setObject:@"07/31/1875" forKey:@"dod"];
        [pres17 setObject:@"Carter's Station, Tennessee" forKey:@"pod"];
        [pres17 setObject:@"04/15/1865" forKey:@"tookOffice"];
        [pres17 setObject:@"03/04/1869" forKey:@"leftOffice"];
        [pres17 setObject:@"1" forKey:@"terms"];
        [pres17 setObject:@"natural causes (stroke)" forKey:@"causeOfDeath"];
        [pres17 setObject:@"N" forKey:@"diedInOffice"];
        [pres17 setObject:@"N" forKey:@"assassinated"];
        [pres17 setObject:@"Democratic" forKey:@"politicalParty"];
        [pres17 setObject:@"None" forKey:@"vicePres"];
        [pres17 setObject:@"AndrewJohnson.png" forKey:@"photo"];

        NSMutableDictionary *pres18 = [[NSMutableDictionary alloc]initWithCapacity:14];
        [pres18 setObject:@"Hiram Ulysses Grant" forKey:@"name"];
        [pres18 setObject:@"04/27/1822" forKey:@"dob"];
        [pres18 setObject:@"Point Pleasant, Ohio" forKey:@"pob"];
        [pres18 setObject:@"07/23/1885" forKey:@"dod"];
        [pres18 setObject:@"Mount McGregor, New York" forKey:@"pod"];
        [pres18 setObject:@"03/04/1869" forKey:@"tookOffice"];
        [pres18 setObject:@"03/04/1877" forKey:@"leftOffice"];
        [pres18 setObject:@"2" forKey:@"terms"];
        [pres18 setObject:@"natural causes (throat cancer)" forKey:@"causeOfDeath"];
        [pres18 setObject:@"N" forKey:@"diedInOffice"];
        [pres18 setObject:@"N" forKey:@"assassinated"];
        [pres18 setObject:@"Republican" forKey:@"politicalParty"];
        [pres18 setObject:@"Schuyler Colfax; Henry Wilson" forKey:@"vicePres"];
        [pres18 setObject:@"UlyssesGrant.png" forKey:@"photo"];

        NSMutableDictionary *pres19 = [[NSMutableDictionary alloc]initWithCapacity:14];
        [pres19 setObject:@"Rutherford Birchard Hayes" forKey:@"name"];
        [pres19 setObject:@"10/04/1822" forKey:@"dob"];
        [pres19 setObject:@"Delaware, Ohio" forKey:@"pob"];
        [pres19 setObject:@"01/17/1893" forKey:@"dod"];
        [pres19 setObject:@"Fremont, Ohio" forKey:@"pod"];
        [pres19 setObject:@"03/04/1977" forKey:@"tookOffice"];
        [pres19 setObject:@"03/04/1881" forKey:@"leftOffice"];
        [pres19 setObject:@"1" forKey:@"terms"];
        [pres19 setObject:@"natural causes (heart attack)" forKey:@"causeOfDeath"];
        [pres19 setObject:@"N" forKey:@"diedInOffice"];
        [pres19 setObject:@"N" forKey:@"assassinated"];
        [pres19 setObject:@"Republican" forKey:@"politicalParty"];
        [pres19 setObject:@"William Wheeler" forKey:@"vicePres"];
        [pres19 setObject:@"RutherfordHayes.png" forKey:@"photo"];

        NSMutableDictionary *pres20 = [[NSMutableDictionary alloc]initWithCapacity:14];
        [pres20 setObject:@"James Abram Garfield" forKey:@"name"];
        [pres20 setObject:@"11/19/1831" forKey:@"dob"];
        [pres20 setObject:@"Orange, Ohio" forKey:@"pob"];
        [pres20 setObject:@"09/19/1881" forKey:@"dod"];
        [pres20 setObject:@"Elberon, New Jersey" forKey:@"pod"];
        [pres20 setObject:@"03/04/1881" forKey:@"tookOffice"];
        [pres20 setObject:@"09/19/1881" forKey:@"leftOffice"];
        [pres20 setObject:@"1" forKey:@"terms"];
        [pres20 setObject:@"gunshot wound" forKey:@"causeOfDeath"];
        [pres20 setObject:@"Y" forKey:@"diedInOffice"];
        [pres20 setObject:@"Y" forKey:@"assassinated"];
        [pres20 setObject:@"Republican" forKey:@"politicalParty"];
        [pres20 setObject:@"Chester A Arthur" forKey:@"vicePres"];
        [pres20 setObject:@"JamesGarfield.png" forKey:@"photo"];

        NSMutableDictionary *pres21 = [[NSMutableDictionary alloc]initWithCapacity:14];
        [pres21 setObject:@"Chester Alan Arthur" forKey:@"name"];
        [pres21 setObject:@"10/05/1829" forKey:@"dob"];
        [pres21 setObject:@"Fairfield, Vermont" forKey:@"pob"];
        [pres21 setObject:@"11/18/1886" forKey:@"dod"];
        [pres21 setObject:@"New York, New York" forKey:@"pod"];
        [pres21 setObject:@"09/19/1881" forKey:@"tookOffice"];
        [pres21 setObject:@"03/04/1885" forKey:@"leftOffice"];
        [pres21 setObject:@"1" forKey:@"terms"];
        [pres21 setObject:@"natural causes (stroke)" forKey:@"causeOfDeath"];
        [pres21 setObject:@"N" forKey:@"diedInOffice"];
        [pres21 setObject:@"N" forKey:@"assassinated"];
        [pres21 setObject:@"Republican" forKey:@"politicalParty"];
        [pres21 setObject:@"None" forKey:@"vicePres"];
        [pres21 setObject:@"ChesterArthur.png" forKey:@"photo"];

        NSMutableDictionary *pres22 = [[NSMutableDictionary alloc]initWithCapacity:14];
        [pres22 setObject:@"Grover Cleveland" forKey:@"name"];
        [pres22 setObject:@"03/18/1837" forKey:@"dob"];
        [pres22 setObject:@"Caldwell, New Jersey" forKey:@"pob"];
        [pres22 setObject:@"06/24/1908" forKey:@"dod"];
        [pres22 setObject:@"Princeton, New Jersey" forKey:@"pod"];
        [pres22 setObject:@"03/04/1885" forKey:@"tookOffice"];
        [pres22 setObject:@"03/04/1889" forKey:@"leftOffice"];
        [pres22 setObject:@"2" forKey:@"terms"];
        [pres22 setObject:@"natural causes (heart attack)" forKey:@"causeOfDeath"];
        [pres22 setObject:@"N" forKey:@"diedInOffice"];
        [pres22 setObject:@"N" forKey:@"assassinated"];
        [pres22 setObject:@"Democratic" forKey:@"politicalParty"];
        [pres22 setObject:@"Thomas A. Hendricks; None" forKey:@"vicePres"];
        [pres22 setObject:@"GroverCleveland2.png" forKey:@"photo"];

        NSMutableDictionary *pres23 = [[NSMutableDictionary alloc]initWithCapacity:14];
        [pres23 setObject:@"Benjamin Harrison" forKey:@"name"];
        [pres23 setObject:@"08/20/1833" forKey:@"dob"];
        [pres23 setObject:@"North Bend, Ohio" forKey:@"pob"];
        [pres23 setObject:@"03/13/1901" forKey:@"dod"];
        [pres23 setObject:@"Indianapolis, INdiana" forKey:@"pod"];
        [pres23 setObject:@"03/04/1889" forKey:@"tookOffice"];
        [pres23 setObject:@"03/04/1893" forKey:@"leftOffice"];
        [pres23 setObject:@"1" forKey:@"terms"];
        [pres23 setObject:@"natural causes (influenza and pneumonia)" forKey:@"causeOfDeath"];
        [pres23 setObject:@"N" forKey:@"diedInOffice"];
        [pres23 setObject:@"N" forKey:@"assassinated"];
        [pres23 setObject:@"Republican" forKey:@"politicalParty"];
        [pres23 setObject:@"Levi P. Morton" forKey:@"vicePres"];
        [pres23 setObject:@"BenjaminHarrison.png" forKey:@"photo"];

        NSMutableDictionary *pres24 = [[NSMutableDictionary alloc]initWithCapacity:14];
        [pres24 setObject:@"Grover Cleveland" forKey:@"name"];
        [pres24 setObject:@"03/18/1837" forKey:@"dob"];
        [pres24 setObject:@"Caldwell, New Jersey" forKey:@"pob"];
        [pres24 setObject:@"06/24/1908" forKey:@"dod"];
        [pres24 setObject:@"Princeton, New Jersey" forKey:@"pod"];
        [pres24 setObject:@"03/04/1893" forKey:@"tookOffice"];
        [pres24 setObject:@"03/04/1897" forKey:@"leftOffice"];
        [pres24 setObject:@"2" forKey:@"terms"];
        [pres24 setObject:@"natural causes (heart attack)" forKey:@"causeOfDeath"];
        [pres24 setObject:@"N" forKey:@"diedInOffice"];
        [pres24 setObject:@"N" forKey:@"assassinated"];
        [pres24 setObject:@"Democratic" forKey:@"politicalParty"];
        [pres24 setObject:@"Adlai E. Stevenson I" forKey:@"vicePres"];
        [pres24 setObject:@"GroverCleveland.png" forKey:@"photo"];

        NSMutableDictionary *pres25 = [[NSMutableDictionary alloc]initWithCapacity:14];
        [pres25 setObject:@"William McKinley" forKey:@"name"];
        [pres25 setObject:@"01/29/1843" forKey:@"dob"];
        [pres25 setObject:@"Niles, Ohio" forKey:@"pob"];
        [pres25 setObject:@"09/14/1901" forKey:@"dod"];
        [pres25 setObject:@"Buffalo, New York" forKey:@"pod"];
        [pres25 setObject:@"03/04/1897" forKey:@"tookOffice"];
        [pres25 setObject:@"09/14/1901" forKey:@"leftOffice"];
        [pres25 setObject:@"1" forKey:@"terms"];
        [pres25 setObject:@"Gangrene from gunshot wounds" forKey:@"causeOfDeath"];
        [pres25 setObject:@"Y" forKey:@"diedInOffice"];
        [pres25 setObject:@"Y" forKey:@"assassinated"];
        [pres25 setObject:@"Republican" forKey:@"politicalParty"];
        [pres25 setObject:@"Garret Hobart; Theodore Roosevelt" forKey:@"vicePres"];
        [pres25 setObject:@"WilliamMcKinley.png" forKey:@"photo"];

        NSMutableDictionary *pres26 = [[NSMutableDictionary alloc]initWithCapacity:14];
        [pres26 setObject:@"Theodore Roosevelt" forKey:@"name"];
        [pres26 setObject:@"10/27/1858" forKey:@"dob"];
        [pres26 setObject:@"New York City, New York" forKey:@"pob"];
        [pres26 setObject:@"01/06/1919" forKey:@"dod"];
        [pres26 setObject:@"Oyster Bay, New York" forKey:@"pod"];
        [pres26 setObject:@"09/14/1901" forKey:@"tookOffice"];
        [pres26 setObject:@"03/04/1909" forKey:@"leftOffice"];
        [pres26 setObject:@"2" forKey:@"terms"];
        [pres26 setObject:@"natural causes (heart attack)" forKey:@"causeOfDeath"];
        [pres26 setObject:@"N" forKey:@"diedInOffice"];
        [pres26 setObject:@"N" forKey:@"assassinated"];
        [pres26 setObject:@"Republican" forKey:@"politicalParty"];
        [pres26 setObject:@"Charles W. Fairbanks" forKey:@"vicePres"];
        [pres26 setObject:@"TheodoreRoosevelt.png" forKey:@"photo"];

        NSMutableDictionary *pres27 = [[NSMutableDictionary alloc]initWithCapacity:14];
        [pres27 setObject:@"William Howard Taft" forKey:@"name"];
        [pres27 setObject:@"09/15/1857" forKey:@"dob"];
        [pres27 setObject:@"Cincinnati, Ohio" forKey:@"pob"];
        [pres27 setObject:@"03/08/1930" forKey:@"dod"];
        [pres27 setObject:@"Washington, D.C." forKey:@"pod"];
        [pres27 setObject:@"03/04/1909" forKey:@"tookOffice"];
        [pres27 setObject:@"03/04/1913" forKey:@"leftOffice"];
        [pres27 setObject:@"1" forKey:@"terms"];
        [pres27 setObject:@"natural causes" forKey:@"causeOfDeath"];
        [pres27 setObject:@"N" forKey:@"diedInOffice"];
        [pres27 setObject:@"N" forKey:@"assassinated"];
        [pres27 setObject:@"Republican" forKey:@"politicalParty"];
        [pres27 setObject:@"James S. Sherman; None" forKey:@"vicePres"];
        [pres27 setObject:@"WilliamHTaft.png" forKey:@"photo"];

        NSMutableDictionary *pres28 = [[NSMutableDictionary alloc]initWithCapacity:14];
        [pres28 setObject:@"Thomas Woodrow Wilson" forKey:@"name"];
        [pres28 setObject:@"12/28/1856" forKey:@"dob"];
        [pres28 setObject:@"Staunton, Virginia" forKey:@"pob"];
        [pres28 setObject:@"02/03/1924" forKey:@"dod"];
        [pres28 setObject:@"Washington, D.C." forKey:@"pod"];
        [pres28 setObject:@"03/04/1913" forKey:@"tookOffice"];
        [pres28 setObject:@"03/04/1921" forKey:@"leftOffice"];
        [pres28 setObject:@"2" forKey:@"terms"];
        [pres28 setObject:@"natural causes" forKey:@"causeOfDeath"];
        [pres28 setObject:@"N" forKey:@"diedInOffice"];
        [pres28 setObject:@"N" forKey:@"assassinated"];
        [pres28 setObject:@"Democratic" forKey:@"politicalParty"];
        [pres28 setObject:@"Thomas R. Marshall" forKey:@"vicePres"];
        [pres28 setObject:@"WoodrowWilson.png" forKey:@"photo"];

        NSMutableDictionary *pres29 = [[NSMutableDictionary alloc]initWithCapacity:14];
        [pres29 setObject:@"Warren Gamaliel Harding" forKey:@"name"];
        [pres29 setObject:@"11/02/1865" forKey:@"dob"];
        [pres29 setObject:@"Blooming Grove, Ohio" forKey:@"pob"];
        [pres29 setObject:@"08/02/1923" forKey:@"dod"];
        [pres29 setObject:@"San Francisco, California" forKey:@"pod"];
        [pres29 setObject:@"03/04/1921" forKey:@"tookOffice"];
        [pres29 setObject:@"08/02/1923" forKey:@"leftOffice"];
        [pres29 setObject:@"1" forKey:@"terms"];
        [pres29 setObject:@"natural causes (pneumonia)" forKey:@"causeOfDeath"];
        [pres29 setObject:@"Y" forKey:@"diedInOffice"];
        [pres29 setObject:@"N" forKey:@"assassinated"];
        [pres29 setObject:@"Republican" forKey:@"politicalParty"];
        [pres29 setObject:@"Calvin Coolidge" forKey:@"vicePres"];
        [pres29 setObject:@"WarrenHarding.png" forKey:@"photo"];

        NSMutableDictionary *pres30 = [[NSMutableDictionary alloc]initWithCapacity:14];
        [pres30 setObject:@"John Calvin Coolidge" forKey:@"name"];
        [pres30 setObject:@"07/04/1872" forKey:@"dob"];
        [pres30 setObject:@"Plymouth Notch, Vermont" forKey:@"pob"];
        [pres30 setObject:@"01/05/1933" forKey:@"dod"];
        [pres30 setObject:@"Northampton, Massachusetts" forKey:@"pod"];
        [pres30 setObject:@"08/02/1923" forKey:@"tookOffice"];
        [pres30 setObject:@"03/04/1929" forKey:@"leftOffice"];
        [pres30 setObject:@"2" forKey:@"terms"];
        [pres30 setObject:@"natural causes (heart attack)" forKey:@"causeOfDeath"];
        [pres30 setObject:@"N" forKey:@"diedInOffice"];
        [pres30 setObject:@"N" forKey:@"assassinated"];
        [pres30 setObject:@"Republican" forKey:@"politicalParty"];
        [pres30 setObject:@"Charles G. Dawes" forKey:@"vicePres"];
        [pres30 setObject:@"CalvinCoolidge.png" forKey:@"photo"];
        
        NSMutableDictionary *pres31 = [[NSMutableDictionary alloc]initWithCapacity:14];
        [pres31 setObject:@"Herbert Clark Hoover" forKey:@"name"];
        [pres31 setObject:@"08/10/1874" forKey:@"dob"];
        [pres31 setObject:@"West Branch, Iowa" forKey:@"pob"];
        [pres31 setObject:@"10/20/1964" forKey:@"dod"];
        [pres31 setObject:@"New York City, New York" forKey:@"pod"];
        [pres31 setObject:@"03/04/1929" forKey:@"tookOffice"];
        [pres31 setObject:@"03/04/1933" forKey:@"leftOffice"];
        [pres31 setObject:@"1" forKey:@"terms"];
        [pres31 setObject:@"natural causes (internal bleeding)" forKey:@"causeOfDeath"];
        [pres31 setObject:@"N" forKey:@"diedInOffice"];
        [pres31 setObject:@"N" forKey:@"assassinated"];
        [pres31 setObject:@"Republican" forKey:@"politicalParty"];
        [pres31 setObject:@"Charles Curtis" forKey:@"vicePres"];
        [pres31 setObject:@"HerbertHoover.png" forKey:@"photo"];

        NSMutableDictionary *pres32 = [[NSMutableDictionary alloc]initWithCapacity:14];
        [pres32 setObject:@"Franklin Delano Roosevelt" forKey:@"name"];
        [pres32 setObject:@"01/30/1882" forKey:@"dob"];
        [pres32 setObject:@"Hyde Park, New York" forKey:@"pob"];
        [pres32 setObject:@"04/12/1945" forKey:@"dod"];
        [pres32 setObject:@"Warm Springs, Georgia" forKey:@"pod"];
        [pres32 setObject:@"03/04/1933" forKey:@"tookOffice"];
        [pres32 setObject:@"04/12/1945" forKey:@"leftOffice"];
        [pres32 setObject:@"3" forKey:@"terms"];
        [pres32 setObject:@"natural causes (stroke)" forKey:@"causeOfDeath"];
        [pres32 setObject:@"Y" forKey:@"diedInOffice"];
        [pres32 setObject:@"N" forKey:@"assassinated"];
        [pres32 setObject:@"Democratic" forKey:@"politicalParty"];
        [pres32 setObject:@"John Nance Garner; Henry A. Wallace; Harry S. Truman" forKey:@"vicePres"];
        [pres32 setObject:@"FranklinRoosevelt.png" forKey:@"photo"];

        NSMutableDictionary *pres33 = [[NSMutableDictionary alloc]initWithCapacity:14];
        [pres33 setObject:@"Harry S Truman" forKey:@"name"];
        [pres33 setObject:@"05/08/1884" forKey:@"dob"];
        [pres33 setObject:@"Lamar Missouri" forKey:@"pob"];
        [pres33 setObject:@"12/26/1972" forKey:@"dod"];
        [pres33 setObject:@"Kansas City, Missouri" forKey:@"pod"];
        [pres33 setObject:@"04/12/1945" forKey:@"tookOffice"];
        [pres33 setObject:@"01/20/1953" forKey:@"leftOffice"];
        [pres33 setObject:@"2" forKey:@"terms"];
        [pres33 setObject:@"natural causes (pneumonia)" forKey:@"causeOfDeath"];
        [pres33 setObject:@"N" forKey:@"diedInOffice"];
        [pres33 setObject:@"N" forKey:@"assassinated"];
        [pres33 setObject:@"Democratic" forKey:@"politicalParty"];
        [pres33 setObject:@"Alben W. Barkley" forKey:@"vicePres"];
        [pres33 setObject:@"HarryTruman.png" forKey:@"photo"];

        NSMutableDictionary *pres34 = [[NSMutableDictionary alloc]initWithCapacity:14];
        [pres34 setObject:@"Dwight David Eisenhower" forKey:@"name"];
        [pres34 setObject:@"10/14/1890" forKey:@"dob"];
        [pres34 setObject:@"Denison, Texas" forKey:@"pob"];
        [pres34 setObject:@"03/28/1969" forKey:@"dod"];
        [pres34 setObject:@"Washington, D.C." forKey:@"pod"];
        [pres34 setObject:@"01/20/1953" forKey:@"tookOffice"];
        [pres34 setObject:@"01/20/1961" forKey:@"leftOffice"];
        [pres34 setObject:@"2" forKey:@"terms"];
        [pres34 setObject:@"natural causes (congestive heart failure)" forKey:@"causeOfDeath"];
        [pres34 setObject:@"N" forKey:@"diedInOffice"];
        [pres34 setObject:@"N" forKey:@"assassinated"];
        [pres34 setObject:@"Republican" forKey:@"politicalParty"];
        [pres34 setObject:@"Richard Nixon" forKey:@"vicePres"];
        [pres34 setObject:@"DwightEisenhower.png" forKey:@"photo"];

        NSMutableDictionary *pres35 = [[NSMutableDictionary alloc]initWithCapacity:14];
        [pres35 setObject:@"John Fitzgerald Kennedy" forKey:@"name"];
        [pres35 setObject:@"05/29/1917" forKey:@"dob"];
        [pres35 setObject:@"Brookline, Massachusetts" forKey:@"pob"];
        [pres35 setObject:@"11/22/1963" forKey:@"dod"];
        [pres35 setObject:@"Dallas, Texas" forKey:@"pod"];
        [pres35 setObject:@"01/20/1961" forKey:@"tookOffice"];
        [pres35 setObject:@"11/22/1963" forKey:@"leftOffice"];
        [pres35 setObject:@"1" forKey:@"terms"];
        [pres35 setObject:@"gunshot wound" forKey:@"causeOfDeath"];
        [pres35 setObject:@"Y" forKey:@"diedInOffice"];
        [pres35 setObject:@"Y" forKey:@"assassinated"];
        [pres35 setObject:@"Democratic" forKey:@"politicalParty"];
        [pres35 setObject:@"Lyndon Johnson" forKey:@"vicePres"];
        [pres35 setObject:@"JohnKennedy.png" forKey:@"photo"];

        NSMutableDictionary *pres36 = [[NSMutableDictionary alloc]initWithCapacity:14];
        [pres36 setObject:@"Lyndon Baines Johnson" forKey:@"name"];
        [pres36 setObject:@"08/27/1908" forKey:@"dob"];
        [pres36 setObject:@"Stonewall, Texas" forKey:@"pob"];
        [pres36 setObject:@"01/22/1973" forKey:@"dod"];
        [pres36 setObject:@"Stonewall, Texas" forKey:@"pod"];
        [pres36 setObject:@"11/22/1963" forKey:@"tookOffice"];
        [pres36 setObject:@"01/20/1969" forKey:@"leftOffice"];
        [pres36 setObject:@"2" forKey:@"terms"];
        [pres36 setObject:@"natural causes (heart attack)" forKey:@"causeOfDeath"];
        [pres36 setObject:@"N" forKey:@"diedInOffice"];
        [pres36 setObject:@"N" forKey:@"assassinated"];
        [pres36 setObject:@"Democratic" forKey:@"politicalParty"];
        [pres36 setObject:@"Hubert Humphrey" forKey:@"vicePres"];
        [pres36 setObject:@"LyndonJohnson.png" forKey:@"photo"];

        NSMutableDictionary *pres37 = [[NSMutableDictionary alloc]initWithCapacity:14];
        [pres37 setObject:@"Richard Nixon" forKey:@"name"];
        [pres37 setObject:@"01/09/1913" forKey:@"dob"];
        [pres37 setObject:@"Yorba Linda, California" forKey:@"pob"];
        [pres37 setObject:@"04/22/1994" forKey:@"dod"];
        [pres37 setObject:@"New York City, New York" forKey:@"pod"];
        [pres37 setObject:@"01/20/1969" forKey:@"tookOffice"];
        [pres37 setObject:@"08/09/1974" forKey:@"leftOffice"];
        [pres37 setObject:@"2" forKey:@"terms"];
        [pres37 setObject:@"natural causes (stroke)" forKey:@"causeOfDeath"];
        [pres37 setObject:@"N" forKey:@"diedInOffice"];
        [pres37 setObject:@"N" forKey:@"assassinated"];
        [pres37 setObject:@"Republican" forKey:@"politicalParty"];
        [pres37 setObject:@"Spiro Agnew; Gerald Ford" forKey:@"vicePres"];
        [pres37 setObject:@"RichardNixon.png" forKey:@"photo"];

        NSMutableDictionary *pres38 = [[NSMutableDictionary alloc]initWithCapacity:14];
        [pres38 setObject:@"Gerald Rudolph Ford, Jr." forKey:@"name"];
        [pres38 setObject:@"07/14/1913" forKey:@"dob"];
        [pres38 setObject:@"Omaha, Nebraska" forKey:@"pob"];
        [pres38 setObject:@"12/26/2006" forKey:@"dod"];
        [pres38 setObject:@"Ranch Mirage, California" forKey:@"pod"];
        [pres38 setObject:@"08/09/1974" forKey:@"tookOffice"];
        [pres38 setObject:@"01/20/1977" forKey:@"leftOffice"];
        [pres38 setObject:@"1" forKey:@"terms"];
        [pres38 setObject:@"natural causes (arteriosclerosis)" forKey:@"causeOfDeath"];
        [pres38 setObject:@"N" forKey:@"diedInOffice"];
        [pres38 setObject:@"N" forKey:@"assassinated"];
        [pres38 setObject:@"Republican" forKey:@"politicalParty"];
        [pres38 setObject:@"Nelson Rockefeller" forKey:@"vicePres"];
        [pres38 setObject:@"GeraldFord.png" forKey:@"photo"];

        NSMutableDictionary *pres39 = [[NSMutableDictionary alloc]initWithCapacity:14];
        [pres39 setObject:@"James Earl Carter, Jr." forKey:@"name"];
        [pres39 setObject:@"10/01/1924" forKey:@"dob"];
        [pres39 setObject:@"Plains, Georgia" forKey:@"pob"];
        [pres39 setObject:@"" forKey:@"dod"];
        [pres39 setObject:@"" forKey:@"pod"];
        [pres39 setObject:@"01/20/1977" forKey:@"tookOffice"];
        [pres39 setObject:@"01/20/1981" forKey:@"leftOffice"];
        [pres39 setObject:@"1" forKey:@"terms"];
        [pres39 setObject:@"" forKey:@"causeOfDeath"];
        [pres39 setObject:@"N" forKey:@"diedInOffice"];
        [pres39 setObject:@"N" forKey:@"assassinated"];
        [pres39 setObject:@"Democratic" forKey:@"politicalParty"];
        [pres39 setObject:@"Walter Mondale" forKey:@"vicePres"];
        [pres39 setObject:@"JimmyCarter.png" forKey:@"photo"];

        NSMutableDictionary *pres40 = [[NSMutableDictionary alloc]initWithCapacity:14];
        [pres40 setObject:@"Ronald Reagan" forKey:@"name"];
        [pres40 setObject:@"02/06/1911" forKey:@"dob"];
        [pres40 setObject:@"Tampico, Illinois" forKey:@"pob"];
        [pres40 setObject:@"06/05/2004" forKey:@"dod"];
        [pres40 setObject:@"Bel Air, California" forKey:@"pod"];
        [pres40 setObject:@"01/20/1981" forKey:@"tookOffice"];
        [pres40 setObject:@"01/20/1988" forKey:@"leftOffice"];
        [pres40 setObject:@"2" forKey:@"terms"];
        [pres40 setObject:@"natural causes (pneumonia)" forKey:@"causeOfDeath"];
        [pres40 setObject:@"N" forKey:@"diedInOffice"];
        [pres40 setObject:@"N" forKey:@"assassinated"];
        [pres40 setObject:@"Republican" forKey:@"politicalParty"];
        [pres40 setObject:@"George Herbert Walker Bush" forKey:@"vicePres"];
        [pres40 setObject:@"RonaldReagan.png" forKey:@"photo"];

        NSMutableDictionary *pres41 = [[NSMutableDictionary alloc]initWithCapacity:14];
        [pres41 setObject:@"George Herbert Walker Bush" forKey:@"name"];
        [pres41 setObject:@"06/12/1924" forKey:@"dob"];
        [pres41 setObject:@"Milton, Massachusetts" forKey:@"pob"];
        [pres41 setObject:@"" forKey:@"dod"];
        [pres41 setObject:@"" forKey:@"pod"];
        [pres41 setObject:@"01/20/1989" forKey:@"tookOffice"];
        [pres41 setObject:@"01/20/1993" forKey:@"leftOffice"];
        [pres41 setObject:@"1" forKey:@"terms"];
        [pres41 setObject:@"" forKey:@"causeOfDeath"];
        [pres41 setObject:@"N" forKey:@"diedInOffice"];
        [pres41 setObject:@"N" forKey:@"assassinated"];
        [pres41 setObject:@"Republican" forKey:@"politicalParty"];
        [pres41 setObject:@"Dan Quayle" forKey:@"vicePres"];
        [pres41 setObject:@"GeorgeHWBush.pgn " forKey:@"photo"];

        NSMutableDictionary *pres42 = [[NSMutableDictionary alloc]initWithCapacity:14];
        [pres42 setObject:@"William Jefferson Clinton" forKey:@"name"];
        [pres42 setObject:@"08/19/1946" forKey:@"dob"];
        [pres42 setObject:@"Hope, Arkansas" forKey:@"pob"];
        [pres42 setObject:@"" forKey:@"dod"];
        [pres42 setObject:@"" forKey:@"pod"];
        [pres42 setObject:@"01/20/1993" forKey:@"tookOffice"];
        [pres42 setObject:@"01/20/2001" forKey:@"leftOffice"];
        [pres42 setObject:@"2" forKey:@"terms"];
        [pres42 setObject:@"" forKey:@"causeOfDeath"];
        [pres42 setObject:@"N" forKey:@"diedInOffice"];
        [pres42 setObject:@"N" forKey:@"assassinated"];
        [pres42 setObject:@"Democratic" forKey:@"politicalParty"];
        [pres42 setObject:@"Al Gore" forKey:@"vicePres"];
        [pres42 setObject:@"Clinton.png" forKey:@"photo"];

        NSMutableDictionary *pres43 = [[NSMutableDictionary alloc]initWithCapacity:14];
        [pres43 setObject:@"George W Bush" forKey:@"name"];
        [pres43 setObject:@"07/06/1946" forKey:@"dob"];
        [pres43 setObject:@"New Haven, Connecticut" forKey:@"pob"];
        [pres43 setObject:@"" forKey:@"dod"];
        [pres43 setObject:@"" forKey:@"pod"];
        [pres43 setObject:@"01/20/2001" forKey:@"tookOffice"];
        [pres43 setObject:@"01/20/2009" forKey:@"leftOffice"];
        [pres43 setObject:@"2" forKey:@"terms"];
        [pres43 setObject:@"" forKey:@"causeOfDeath"];
        [pres43 setObject:@"N" forKey:@"diedInOffice"];
        [pres43 setObject:@"N" forKey:@"assassinated"];
        [pres43 setObject:@"Republican" forKey:@"politicalParty"];
        [pres43 setObject:@"Dick Cheney" forKey:@"vicePres"];
        [pres43 setObject:@"GeorgeWBush.png" forKey:@"photo"];

        NSMutableDictionary *pres44 = [[NSMutableDictionary alloc]initWithCapacity:14];
        [pres44 setObject:@"Barack Hussein Obama II" forKey:@"name"];
        [pres44 setObject:@"08/04/1961" forKey:@"dob"];
        [pres44 setObject:@"Honolulu, Hawaii" forKey:@"pob"];
        [pres44 setObject:@"" forKey:@"dod"];
        [pres44 setObject:@"" forKey:@"pod"];
        [pres44 setObject:@"01/20/2009" forKey:@"tookOffice"];
        [pres44 setObject:@"" forKey:@"leftOffice"];
        [pres44 setObject:@"1" forKey:@"terms"];
        [pres44 setObject:@"" forKey:@"causeOfDeath"];
        [pres44 setObject:@"" forKey:@"diedInOffice"];
        [pres44 setObject:@"" forKey:@"assassinated"];
        [pres44 setObject:@"Democratic" forKey:@"politicalParty"];
        [pres44 setObject:@"Joseph Robinette Biden, Jr." forKey:@"vicePres"];
        [pres44 setObject:@"BarackObama.png" forKey:@"photo"];

        NSArray *pres = [[NSArray alloc]initWithObjects:pres1, pres2, pres3, pres4, pres5, pres6, pres7, pres8, pres9, pres10, pres11, pres12, pres13, pres14, pres15, pres16, pres17, pres18, pres19, pres20, pres21, pres22, pres23, pres24, pres25, pres26, pres27, pres28, pres29, pres30, pres31, pres32, pres33, pres34, pres35, pres36, pres37, pres38, pres39, pres40, pres41, pres42, pres43, pres44, nil];
        
        [pres1 release];
        [pres2 release];
        [pres3 release];
        [pres4 release];
        [pres5 release];
        [pres6 release];
        [pres7 release];
        [pres8 release];
        [pres9 release];
        [pres10 release];
        [pres11 release];
        [pres12 release];
        [pres13 release];
        [pres14 release];
        [pres15 release];
        [pres16 release];
        [pres17 release];
        [pres18 release];
        [pres19 release];
        [pres20 release];
        [pres21 release];
        [pres22 release];
        [pres23 release];
        [pres24 release];
        [pres25 release];
        [pres26 release];
        [pres27 release];
        [pres28 release];
        [pres29 release];
        [pres30 release];
        [pres31 release];
        [pres32 release];
        [pres33 release];
        [pres34 release];
        [pres35 release];
        [pres36 release];
        [pres37 release];
        [pres38 release];
        [pres39 release];
        [pres40 release];
        [pres41 release];
        [pres42 release];
        [pres43 release];
        [pres44 release];

        self.presInfo = pres;
        [pres release];
        
        // Initialization code here.
    }
    
    return self;
}

- (void) dealloc {
    self.presInfo = nil;
    [presInfo release];
    [super dealloc];
}
@end